// Map country names and codes to flag emojis
const countryToFlag: Record<string, string> = {
	// Common countries
	US: "🇺🇸",
	USA: "🇺🇸",
	"United States": "🇺🇸",
	Canada: "🇨🇦",
	CA: "🇨🇦",
	"United Kingdom": "🇬🇧",
	UK: "🇬🇧",
	GB: "🇬🇧",
	Australia: "🇦🇺",
	AU: "🇦🇺",
	Germany: "🇩🇪",
	DE: "🇩🇪",
	France: "🇫🇷",
	FR: "🇫🇷",
	Japan: "🇯🇵",
	JP: "🇯🇵",
	China: "🇨🇳",
	CN: "🇨🇳",
	India: "🇮🇳",
	IN: "🇮🇳",
	Brazil: "🇧🇷",
	BR: "🇧🇷",
	Russia: "🇷🇺",
	RU: "🇷🇺",
	Mexico: "🇲🇽",
	MX: "🇲🇽",
	Italy: "🇮🇹",
	IT: "🇮🇹",
	Spain: "🇪🇸",
	ES: "🇪🇸",
	Netherlands: "🇳🇱",
	NL: "🇳🇱",
	Switzerland: "🇨🇭",
	CH: "🇨🇭",
	Sweden: "🇸🇪",
	SE: "🇸🇪",
	Norway: "🇳🇴",
	NO: "🇳🇴",
	Denmark: "🇩🇰",
	DK: "🇩🇰",
	Finland: "🇫🇮",
	FI: "🇫🇮",
	"South Korea": "🇰🇷",
	KR: "🇰🇷",
	"South Africa": "🇿🇦",
	ZA: "🇿🇦",
	Argentina: "🇦🇷",
	AR: "🇦🇷",
	Chile: "🇨🇱",
	CL: "🇨🇱",
	Peru: "🇵🇪",
	PE: "🇵🇪",
	Colombia: "🇨🇴",
	CO: "🇨🇴",
	Venezuela: "🇻🇪",
	VE: "🇻🇪",
	Ecuador: "🇪🇨",
	EC: "🇪🇨",
	Uruguay: "🇺🇾",
	UY: "🇺🇾",
	Paraguay: "🇵🇾",
	PY: "🇵🇾",
	Bolivia: "🇧🇴",
	BO: "🇧🇴",
	Thailand: "🇹🇭",
	TH: "🇹🇭",
	Singapore: "🇸🇬",
	SG: "🇸🇬",
	Malaysia: "🇲🇾",
	MY: "🇲🇾",
	Indonesia: "🇮🇩",
	ID: "🇮🇩",
	Philippines: "🇵🇭",
	PH: "🇵🇭",
	Vietnam: "🇻🇳",
	VN: "🇻🇳",
	"New Zealand": "🇳🇿",
	NZ: "🇳🇿",
	Israel: "🇮🇱",
	IL: "🇮🇱",
	Turkey: "🇹🇷",
	TR: "🇹🇷",
	Egypt: "🇪🇬",
	EG: "🇪🇬",
	Morocco: "🇲🇦",
	MA: "🇲🇦",
	Nigeria: "🇳🇬",
	NG: "🇳🇬",
	Kenya: "🇰🇪",
	KE: "🇰🇪",
	Ghana: "🇬🇭",
	GH: "🇬🇭",
	Ethiopia: "🇪🇹",
	ET: "🇪🇹",
	Uganda: "🇺🇬",
	UG: "🇺🇬",
	Tanzania: "🇹🇿",
	TZ: "🇹🇿",
	Zambia: "🇿🇲",
	ZM: "🇿🇲",
	Zimbabwe: "🇿🇼",
	ZW: "🇿🇼",
	Botswana: "🇧🇼",
	BW: "🇧🇼",
	Namibia: "🇳🇦",
	NA: "🇳🇦",
	Madagascar: "🇲🇬",
	MG: "🇲🇬",
	Mauritius: "🇲🇺",
	MU: "🇲🇺",
	Seychelles: "🇸🇨",
	SC: "🇸🇨",
	Comoros: "🇰🇲",
	KM: "🇰🇲",
	Réunion: "🇷🇪",
	RE: "🇷🇪",
	Mayotte: "🇾🇹",
	YT: "🇾🇹",
	"Côte d'Ivoire": "🇨🇮",
	CI: "🇨🇮",
	Guinea: "🇬🇳",
	GN: "🇬🇳",
	Mali: "🇲🇱",
	ML: "🇲🇱",
	"Burkina Faso": "🇧🇫",
	BF: "🇧🇫",
	Niger: "🇳🇪",
	NE: "🇳🇪",
	Chad: "🇹🇩",
	TD: "🇹🇩",
	Sudan: "🇸🇩",
	SD: "🇸🇩",
	"South Sudan": "🇸🇸",
	SS: "🇸🇸",
	"Central African Republic": "🇨🇫",
	CF: "🇨🇫",
	Cameroon: "🇨🇲",
	CM: "🇨🇲",
	"Equatorial Guinea": "🇬🇶",
	GQ: "🇬🇶",
	Gabon: "🇬🇦",
	GA: "🇬🇦",
	"Republic of the Congo": "🇨🇬",
	CG: "🇨🇬",
	"Democratic Republic of the Congo": "🇨🇩",
	CD: "🇨🇩",
	Angola: "🇦🇴",
	AO: "🇦🇴",
	"Papua New Guinea": "🇵🇬",
	PG: "🇵🇬",
	Fiji: "🇫🇯",
	FJ: "🇫🇯",
	Tonga: "🇹🇴",
	TO: "🇹🇴",
	Samoa: "🇼🇸",
	WS: "🇼🇸",
	Vanuatu: "🇻🇺",
	VU: "🇻🇺",
	"Solomon Islands": "🇸🇧",
	SB: "🇸🇧",
	Kiribati: "🇰🇮",
	KI: "🇰🇮",
	Tuvalu: "🇹🇻",
	TV: "🇹🇻",
	Nauru: "🇳🇷",
	NR: "🇳🇷",
	Palau: "🇵🇼",
	PW: "🇵🇼",
	"Marshall Islands": "🇲🇭",
	MH: "🇲🇭",
	"Federated States of Micronesia": "🇫🇲",
	FM: "🇫🇲",
	Guam: "🇬🇺",
	GU: "🇬🇺",
	BD: "🇧🇩",
	Bangladesh: "🇧🇩",
};

export function getCountryFlag(country: string): string {
	// Try exact match first
	const flag = countryToFlag[country];
	if (flag) return flag;

	// Try case-insensitive match
	const lowerCountry = country.toLowerCase();
	for (const [key, value] of Object.entries(countryToFlag)) {
		if (key.toLowerCase() === lowerCountry) {
			return value;
		}
	}

	// Default to globe icon if no flag found
	return "🌍";
}

import { TIMEZONE_DATA } from "../timezones";

export const getCountryForTimezone = (timezoneId: string): string => {
	const timezoneData = TIMEZONE_DATA.find(
		(tz) => tz.id === timezoneId
	);
	return timezoneData?.country || "Unknown";
};
